events {}

http {
    server {
        listen 4433 ssl;
        server_name tls-server;

        ssl_certificate     /opt/nginx/certs/server.crt;
        ssl_certificate_key /opt/nginx/certs/server.key;
        ssl_protocols TLSv1.3;
        ssl_ecdh_curve X25519:mlkem768:X25519MLKEM768;

        location / {
            return 200 'TLS Connection Established.\n';
            add_header Content-Type text/plain;
        }
    }
}
